DATA:
    image: tianon/true
    volumes:
        - /var/lib/postgresql/data

dbhost:
    image: postgres:9.4
    restart: always
    volumes_from:
        - DATA
    environment:
        ## change password here and in cms-installer.ini
        POSTGRES_USER: djangocms
        POSTGRES_PASSWORD: PASS7jed6an2pas1yug9WORD
uwsgi:
    build: .
    restart: always
    environment:
        ## change password, email & hosts
        ADMIN_USER: admin
        ADMIN_PASSWD: djangocms321
        ADMIN_EMAIL: admin@example.com
        #ALLOWED_HOSTS: ["*"]
        #ALLOWED_HOSTS: [".example.com", ".example.org", "127.0.0.1"]
        ALLOWED_HOSTS: [".lightinasia.org"]
        MODE: production
    volumes:
        - ./cms-project:/cms
    links:
        - dbhost:dbhost
    ports:
        - "8200:8000"

nginx:
    image: nginx:latest
    restart: always
    volumes_from:
        - uwsgi
    volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
        - "280:80"