#!/bin/bash
read -r -p "This will delete all data & cms files. Are you sure? [yes/N] " response
response=${response,,}    # tolower
if [[ $response =~ ^(yes)$ ]]
	docker-compose stop
	docker-compose rm -f
	rm -rf cms-project
	docker-compose build
	docker-compose up -d
	docker-compose logs
	docker logs djangocms_uwsgi_1
fi
