#!/bin/bash
set -e
read -r -p "THIS WILL DELETE THE CONTAINERS, DATA AND CMS-PROJECT FILES based on ${PWD} - Are you sure? [yes/N] " response
response=${response,,}    # tolower
if [[ $response =~ ^(yes)$ ]]; then
	docker-compose stop
	docker-compose rm -f
	echo "removing cms-project"
    rm -rf cms-project/
	docker-compose build
	docker-compose up -d
    set +e
	docker-compose logs
	docker logs djangocms_uwsgi_1
	read -r -p "Enter djangocms_uwsgi_1 container with docker exec? [y/N] " response
	response=${response,,}    # tolower
	if [[ $response =~ ^(yes|y)$ ]]; then
	    docker exec -it djangocms_uwsgi_1 bash
	fi
fi
